### ISSUE TITLE
fscale argument passing

### ISSUE THREAD

**Issue by crmcrae** [Boulder-Cryogenic-Quantum-Testbed/scresonators#137]
fscale can be passed in two ways: through Resonator.from_file and VNA_sweep.from_file. 
fscale passed through Resonator.from_file overwrites Resonator.fscale.
We need to determine the best way to pass fscale without the risk of it being overwritten elsewhere.

**Comment by nickkprice** [comment]
I think I see what you mean. For the use case of someone that has multiple files to parse through that all want the same fscale, but without defining the fscale with every from_file call?

**Comment by nmaterise** [comment]
I think we were also concerned about the general usage of `fscale` from a user interface point of view. I was wondering if you had intended `fscale` to be a member of the `Resonator` class or a stand-alone argument of `Resonator.from_file()` that wraps `VNA_sweep.from_file()`

**Comment by nickkprice** [comment]
I was generally keeping most arguments as attributes of Resonator since that's the interface with the rest of the code, not knowing that fscale was something only relevant to initial reading-in of data. With that in mind, I'll change it to a stand-along argument for the from_file calls, and remove it as a Resonator attribute.

**Comment by nmaterise** [comment]
This was fixed by #138.
