### ISSUE TITLE
Output bugs

### ISSUE THREAD

**Issue by UserBegi** [Boulder-Cryogenic-Quantum-Testbed/scresonators#174]
![image](https://github.com/Boulder-Cryogenic-Quantum-Testbed/scresonators/assets/140977325/465dc3d2-be9b-451d-b80a-1bf555f347b8)
The new updates cause the output layout error, including misplaced legends and labels of the circle fitting plot, wrong scale, and label of the phase plot. Can someone help? Also, is there an option to output png images instead of pdf files?

Thanks.

**Comment by scottito** [comment]
This issue is probably arising from the incomplete separation of fitting and plotting. [PR #166](https://github.com/Boulder-Cryogenic-Quantum-Testbed/scresonators/pull/166) divided Sdata into two Python files, but there are still remnants of plotting in the 'fit' function. I will keep investigating and try to find a fix. In the meantime, reverting to [Commit 04b9561](https://github.com/Boulder-Cryogenic-Quantum-Testbed/scresonators/commit/04b95618dc419463c105c6d2956adea801f406a3) should put you at a version of the code predating this problem.
