### ISSUE TITLE
Standard resonator data format

### ISSUE THREAD

**Issue by crmcrae** [Boulder-Cryogenic-Quantum-Testbed/scresonators#19]
Hi all,

Due to community feedback about issues with fitting a variety of data formats, I went through the datasets we have so far and compiled guidelines for a standard data format. Going forward, we hope that everyone can share their data in the following format:

Three column .csv file starting in row 1, with no empty rows between data.
Data should be the raw data with no normalization or frequency shift.

Column 1:
Monotonically increasing frequency in GHz

Column 2:
Magnitude of S21 in dB (log mag)

Column 3:
Phase of S21 in radians

Other info to be included in a .txt accompanying the data (encouraged but not required):
Input power (dBm)
Number of averages
IFBW
Fridge temperature (mK)
Type of device (materials, design geometry, etc.)

Please let me know if you have any questions or feedback about the guidelines. We're still in the early stages of this effort so any comments would be very helpful.

The NIST and Google data should be in the correct format already, and the GitHub will be updated when other datasets are reformatted.

Thanks!

**Comment by joshmutus** [comment]
This is a great start to regularizing things. 
The only suggestion I'd make is the accompanying text file use something like JSON or XML to make it easy to import from the code side of things.

**Comment by joshmutus** [comment]
So there's a standard adopted by Keysight that [exists](https://ibis.org/connector/touchstone_spec11.pdf). Perhaps we should look at using that

**Comment by FaustinCarter** [comment]
All the spice simulators will import touchstone as does scikit-rf. So this
is a good idea.

**Comment by crmcrae** [comment]
I agree, this looks great!
@mullinska let's implement the Keysight Touchstone format as the standard input for our code.

**Comment by mullinska** [comment]
Great. I'm glad we could get that figured out. I'll get to work on updating this as soon as possible.

**Comment by mullinska** [comment]
Hi guys, I just wanted to let you all know that I've encountered a bit of an issue with the Keysight format that we've discussed using. If you look at page 7 example 4 in the link that Josh posted above, you'll notice that the format includes data for S11, S21, S12 and S22 for a 2 port measurement instead of just the S21 that we care about. If we follow the format we would need to figure out some value to put in the columns for the other port combinations, or we could go against the format and only include the columns for S21 data. Of course there may be some other option I haven't listed as well. In any case it would be nice to discuss what to do about this so I can fully integrate it into the code. I've already finished the header reading section so data reading is all I really have left. Please let me know what you all think, thanks.

**Comment by joshmutus** [comment]
Can we fill the other columns with NaN? Does it have anything in the spec for missing data?

**Comment by mullinska** [comment]
Hi @joshmutus , sorry for the late reply. I've looked through the touchstone file syntax and rules in detail. I can't find anything in the document about missing data, but it would appear that as long as we use ASCII characters in the standard range it should be fine. So just typing the letters "NaN" would work, however something like ASCII control character 0 (NULL) would not. There doesn't really appear to be a standard for missing data as far as I can see though. However, my question was more specific to file sizes. I wasn't sure if we needed to specify that every other column besides S21 is blank by putting something like NaN in, or whether we could just only include the column data for S21. After all, including column data for things we don't care about seems like a waste of file space to me, but I wanted to check to make sure.
